# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwO6U24sM3K0XuPDqmAPctEdclxEPc7v
"""

import cv2

img = cv2.imread("images.jpg")

!sudo apt install tesseract-ocr
!pip install pytesseract

from google.colab.patches import cv2_imshow
cv2_imshow(img)

cv2.waitKey(0)

import pytesseract

text = pytesseract.image_to_string(img)

print(text)

